/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksRouteImport } from './routes/works'
import { Route as UiUxDesignRouteImport } from './routes/ui-ux-design'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SaasRouteImport } from './routes/saas'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as MobileAppsRouteImport } from './routes/mobile-apps'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DigitalTransformationRouteImport } from './routes/digital-transformation'
import { Route as CustomSoftwareRouteImport } from './routes/custom-software'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const UiUxDesignRoute = UiUxDesignRouteImport.update({
  id: '/ui-ux-design',
  path: '/ui-ux-design',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasRoute = SaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppsRoute = MobileAppsRouteImport.update({
  id: '/mobile-apps',
  path: '/mobile-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTransformationRoute = DigitalTransformationRouteImport.update({
  id: '/digital-transformation',
  path: '/digital-transformation',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomSoftwareRoute = CustomSoftwareRouteImport.update({
  id: '/custom-software',
  path: '/custom-software',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/custom-software': typeof CustomSoftwareRoute
  '/digital-transformation': typeof DigitalTransformationRoute
  '/faq': typeof FaqRoute
  '/leadership': typeof LeadershipRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/our-story': typeof OurStoryRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/saas': typeof SaasRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/ui-ux-design': typeof UiUxDesignRoute
  '/works': typeof WorksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/custom-software': typeof CustomSoftwareRoute
  '/digital-transformation': typeof DigitalTransformationRoute
  '/faq': typeof FaqRoute
  '/leadership': typeof LeadershipRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/our-story': typeof OurStoryRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/saas': typeof SaasRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/ui-ux-design': typeof UiUxDesignRoute
  '/works': typeof WorksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/custom-software': typeof CustomSoftwareRoute
  '/digital-transformation': typeof DigitalTransformationRoute
  '/faq': typeof FaqRoute
  '/leadership': typeof LeadershipRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/our-story': typeof OurStoryRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/saas': typeof SaasRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/ui-ux-design': typeof UiUxDesignRoute
  '/works': typeof WorksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/custom-software'
    | '/digital-transformation'
    | '/faq'
    | '/leadership'
    | '/mobile-apps'
    | '/our-story'
    | '/pricing'
    | '/resources'
    | '/saas'
    | '/services'
    | '/solutions'
    | '/ui-ux-design'
    | '/works'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/custom-software'
    | '/digital-transformation'
    | '/faq'
    | '/leadership'
    | '/mobile-apps'
    | '/our-story'
    | '/pricing'
    | '/resources'
    | '/saas'
    | '/services'
    | '/solutions'
    | '/ui-ux-design'
    | '/works'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/custom-software'
    | '/digital-transformation'
    | '/faq'
    | '/leadership'
    | '/mobile-apps'
    | '/our-story'
    | '/pricing'
    | '/resources'
    | '/saas'
    | '/services'
    | '/solutions'
    | '/ui-ux-design'
    | '/works'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CustomSoftwareRoute: typeof CustomSoftwareRoute
  DigitalTransformationRoute: typeof DigitalTransformationRoute
  FaqRoute: typeof FaqRoute
  LeadershipRoute: typeof LeadershipRoute
  MobileAppsRoute: typeof MobileAppsRoute
  OurStoryRoute: typeof OurStoryRoute
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRoute
  SaasRoute: typeof SaasRoute
  ServicesRoute: typeof ServicesRoute
  SolutionsRoute: typeof SolutionsRoute
  UiUxDesignRoute: typeof UiUxDesignRoute
  WorksRoute: typeof WorksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-ux-design': {
      id: '/ui-ux-design'
      path: '/ui-ux-design'
      fullPath: '/ui-ux-design'
      preLoaderRoute: typeof UiUxDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas': {
      id: '/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof SaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-apps': {
      id: '/mobile-apps'
      path: '/mobile-apps'
      fullPath: '/mobile-apps'
      preLoaderRoute: typeof MobileAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-transformation': {
      id: '/digital-transformation'
      path: '/digital-transformation'
      fullPath: '/digital-transformation'
      preLoaderRoute: typeof DigitalTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-software': {
      id: '/custom-software'
      path: '/custom-software'
      fullPath: '/custom-software'
      preLoaderRoute: typeof CustomSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CustomSoftwareRoute: CustomSoftwareRoute,
  DigitalTransformationRoute: DigitalTransformationRoute,
  FaqRoute: FaqRoute,
  LeadershipRoute: LeadershipRoute,
  MobileAppsRoute: MobileAppsRoute,
  OurStoryRoute: OurStoryRoute,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRoute,
  SaasRoute: SaasRoute,
  ServicesRoute: ServicesRoute,
  SolutionsRoute: SolutionsRoute,
  UiUxDesignRoute: UiUxDesignRoute,
  WorksRoute: WorksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
